package com.ki960213.domain.facility.model

enum class ChildCareService {
    OUR_NEIGHBORHOOD_GROWING_CENTER,
    CO_PARENTING_ROOM,
    LOCAL_CHILDREN_CENTER,
    CO_PARENTING_SHARING_CENTER,
    YOUTH_AFTER_SCHOOL_ACADEMY,
}
